# fly.toml file generated for doyobi-livebook on 2022-02-28T16:51:56+08:00

app = "doyobi-livebook"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  ELIXIR_ERL_OPTIONS = "-proto_dist inet6_tcp"
  LIVEBOOK_IP = "::"
  LIVEBOOK_ROOT_PATH = "/data"
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  private_network = true

[[mounts]]
  destination = "/data"
  encrypted = false
  source = "livebook_data"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
